name: Prod Smoke Status
on:
  workflow_dispatch:

jobs:
  smoke_status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - run: npm ci
      - run: npx playwright install --with-deps
      - name: E2E (status only)
        run: E2E_BASE_URL="${{ secrets.PRODUCTION_URL }}" npx playwright test tests/status.spec.ts --reporter=line
